# Generated by Django 5.0 on 2024-02-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_rename_reyting_ureyting_remove_savol_javoblar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ureyting',
            options={'ordering': ['-test', '-natija']},
        ),
        migrations.AddField(
            model_name='ureyting',
            name='orin',
            field=models.IntegerField(default=-1),
        ),
    ]
