# Generated by Django 5.0 on 2024-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_alter_ureyting_options_ureyting_orin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ureyting',
            name='savollar',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='ureyting',
            name='natija',
            field=models.IntegerField(default=-1),
        ),
    ]
